//! File templates for navigator scaffolding

use chrono::Utc;

/// Default CLAUDE.md content for a new navigator
pub fn default_claude_md(name: &str, knowledge_base_path: &str) -> String {
    format!(
        r#"# {name} Navigator

## Overview

You are **{name}**, an autonomous navigator with access to a curated knowledge base.

## Knowledge Base

Your knowledge base is located at: `{knowledge_base_path}/`

Always search this directory first when answering questions. Cite specific files and sections in your responses.

## Grounding Rules

**CRITICAL: Every answer must follow these rules:**

1. **Always cite sources** - Reference specific files from your knowledge base
2. **Quote directly** - Use exact quotes from documentation when possible
3. **Never invent information** - If something isn't in your knowledge base, say so
4. **File paths must exist** - Only reference files that actually exist
5. **Be specific** - Include section headings, line numbers when relevant
6. **Acknowledge uncertainty** - If confidence is low, explain why

## Response Format

When answering questions, use the `submit_answer` tool with:
- `answer`: Your grounded response with citations
- `sources`: Array of file references with section and relevance
- `confidence`: Score from 0-1 based on source quality

## Self-Configuration

You can modify your own configuration using the self-configuration tools:
- `get_plugin_config`: View current plugin settings
- `update_plugin_config`: Modify plugin settings

Use these to adapt to user preferences for notifications, check-ins, and integrations.

---

*Generated by Autonav on {timestamp}*
"#,
        name = name,
        knowledge_base_path = knowledge_base_path,
        timestamp = Utc::now().format("%Y-%m-%d")
    )
}

/// Default .gitignore content
pub fn default_gitignore() -> &'static str {
    r#"# Autonav
.autonav-init-progress.json

# Secrets
.env
.env.local
*.pem
*.key

# OS
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# Dependencies
node_modules/

# Logs
*.log
"#
}

/// Default README.md for knowledge base
pub fn knowledge_base_readme(name: &str) -> String {
    format!(
        r#"# {name} Knowledge Base

This directory contains the documentation and knowledge that powers the {name} navigator.

## Structure

Organize your documentation in a way that makes sense for your use case:

```
knowledge-base/
├── README.md           # This file
├── getting-started.md  # Quick start guide
├── concepts/           # Core concepts
├── guides/             # How-to guides
├── reference/          # API/CLI reference
└── troubleshooting/    # Common issues
```

## Best Practices

1. **Be specific** - Include concrete examples and commands
2. **Stay current** - Update docs when things change
3. **Cross-reference** - Link related topics
4. **Version info** - Note which versions docs apply to

## Adding Content

Simply add markdown files to this directory. The navigator will automatically search them when answering questions.

For best results:
- Use clear headings and sections
- Include code examples where relevant
- Keep files focused on single topics
"#,
        name = name
    )
}

/// Template for system-configuration.md (from knowledge pack)
pub fn system_configuration_template(pack_name: &str, pack_description: &str) -> String {
    format!(
        r#"# System Configuration

## Knowledge Pack: {pack_name}

{pack_description}

## Purpose

This navigator is configured with the **{pack_name}** knowledge pack, providing specialized knowledge and capabilities.

## Configuration Notes

- Review and customize `config.json` as needed
- Check `.claude/plugins.json` for plugin settings
- Add your own documentation to `knowledge-base/`

## Getting Started

1. Query the navigator: `autonav query . "Your question here"`
2. Start a chat session: `autonav chat .`
3. Update documentation: `autonav update . "Your update message"`
"#,
        pack_name = pack_name,
        pack_description = pack_description
    )
}

/// Replace template variables in a string
pub fn replace_vars(template: &str, vars: &[(&str, &str)]) -> String {
    let mut result = template.to_string();
    for (key, value) in vars {
        let pattern = format!("{{{{{}}}}}", key);
        result = result.replace(&pattern, value);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_claude_md() {
        let content = default_claude_md("my-nav", "knowledge-base");
        assert!(content.contains("my-nav"));
        assert!(content.contains("knowledge-base"));
        assert!(content.contains("Grounding Rules"));
    }

    #[test]
    fn test_default_gitignore() {
        let content = default_gitignore();
        assert!(content.contains(".env"));
        assert!(content.contains(".DS_Store"));
    }

    #[test]
    fn test_knowledge_base_readme() {
        let content = knowledge_base_readme("test-nav");
        assert!(content.contains("test-nav"));
        assert!(content.contains("Knowledge Base"));
    }

    #[test]
    fn test_replace_vars() {
        let template = "Hello {{name}}, welcome to {{place}}!";
        let result = replace_vars(template, &[("name", "World"), ("place", "Rust")]);
        assert_eq!(result, "Hello World, welcome to Rust!");
    }
}
